config/routes.rb
Rails.application.routes.draw do
  resources :comment_updates
  resources :guests
  resources :comments do
    resources :comment_updates, only: [:new, :create, :index]
  end
  resources :stores
  root 'sessions#index'
  resources :users
  get '/open' => 'comments#open'
  get '/guest_comments' => 'comments#guest_comments'
  get '/find_comment' => 'comments#find'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/store_type' => 'stores#store_type'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :store
    belongs_to :user
    belongs_to :guest
    has_many :comment_updates
    accepts_nested_attributes_for :comment_updates
    validates :case_number, uniqueness: true

    COMMENT_TYPES = ["Complaint", "Compliment", "Inquiry"]
    SOURCE = ["1-800#", "VOICE", "Local"]
    URGENT = ["General", "Urgent"]
    CONTACT_TYPE = ["Phone", "Email", "Mail", "Voice", "Other"]
    ORDER_POINT = ["DT", "FC", "Mobile", "Kiosk", "Delivery", "Other"]
    STATUS = ["Open", "Closed"]

    def guest_attributes=(guest)
        self.guest = Guest.find_or_create_by(first_name: guest[:first_name])
        self.guest.update(guest)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :require_log_in

  # GET /comments
  # GET /comments.json
  def index
    if is_admin || is_ops
      @comments = Comment.all
    else
      redirect_to user_path(session[:user_id]) and return
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
    @comment = Comment.new
    @comment.guest = Guest.new
  end

  # GET /comments/1/edit
  def edit
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
    @comment = Comment.new(comment_params)
    @comment.user_id = session[:user_id]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_path(session[:user_id]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to user_path(session[:user_id]), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to user_path(session[:user_id]), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def open
    if is_admin || is_ops
      @comments = Comment.where("status"=>"Open").order("store_id").order("source").order("visit_date")
      respond_to do |format|
        format.html
        format.json { render json: @comments}
      end
    else
      redirect_to user_path(session[:user_id]) and return
    end
  end

  def find
    @comment = Comment.find_by("case_number": params[:case_number])
    respond_to do |format|
      format.html { redirect_to comment_path(@comment.id)}
      format.json {render json: @comment}
    end
  end

  def guest_comments
    if is_admin || is_ops
      if params[:store]
        @comments = Comment.where("store_id"=>params[:store]).where("guest_id"=> params[:id]).order("visit_date")
      else
        @comments = Comment.where("guest_id"=> params[:id]).order("store_id").order("visit_date")
      end
      respond_to do |format|
        format.html
        format.json {render json: @comments}
      end
    else
      redirect_to user_path(session[:user_id]) and return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:visit_date, :visit_time, :comment_type, :source, :urgent, :case_number, :first_issue, :first_issue_comment, :second_issue, :second_issue_comment, :third_issue, :third_issue_comment, :contact_type, :visit_type, :employee_named, :status, :guest_id, :store_id,
        guest_attributes: [:first_name, :last_name, :phone, :email])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |f| %>
    <%= f.fields_for :guest do |guest| %>
        <%= guest.label :first_name, "First Name" %>
            <%= guest.text_field :first_name, required: "true" %>
        <%= guest.label :last_name, "Last Name" %>
            <%= guest.text_field :last_name, required: "true" %><br>
        <%= guest.label :email, "Email Address" %>
            <%= guest.text_field :email %><br>
        <%= guest.label :email, "Phone" %>
            <%= guest.text_field :phone %><br>
    <% end %>
    <%= f.label :store_id, "Restaurant"%>
    <%= f.collection_select(:store_id, Store.all, :id, :store_number) %>
    <%= f.label :visit_date, "Incident Date"%>
    <%= f.date_field :visit_date, required: "true" %>
    <%= f.label :visit_time, "Incident Time"%>
    <%= f.time_field :visit_time, required: "true" %><br>
    <%= f.label :comment_type, "Type of Comment"%>
    <%= f.select :comment_type, Comment::COMMENT_TYPES, required: "true" %>
    <%= f.label :source, "Source of Comment" %>
    <%= f.select :source, Comment::SOURCE, required: "true" %>
    <%= f.label :urgent, "Urgent or General" %>
    <%= f.select :urgent, Comment::URGENT %><br>
    <%= f.label :case_number, "Case Number" %>
    <%= f.text_field :case_number, required: "true" %><br>
    <%= f.label :first_issue, "Customer Issue 1"%>
    <%= f.text_field :first_issue, required: "true" %><br>
    <%= f.label :first_issue_comment, "Details"%><br>
    <%= f.text_area :first_issue_comment, size: "50 x 4", required: "true"%><br>
    <%= f.label :second_issue, "Customer Issue 2"%>
    <%= f.text_field :second_issue %><br>
    <%= f.label :second_issue_comment, "Details"%><br>
    <%= f.text_area :second_issue_comment, size: "50 x 4"%><br>
    <%= f.label :third_issue, "Customer Issue 3"%>
    <%= f.text_field :third_issue %><br>
    <%= f.label :third_issue_comment, "Details"%><br>
    <%= f.text_area :third_issue_comment, size: "50 x 4" %><br>
    <%= f.label :contact_type, "Contact Type"%>
    <%= f.select :contact_type, Comment::CONTACT_TYPE %>
    <%= f.label :visit_type, "Order Point" %>
    <%= f.select :visit_type, Comment::ORDER_POINT %><br>
    <%= f.label :employee_named, "Employee Named"%>
    <%= f.text_field :employee_named %>
    <%= f.label :status, "Status"%>
    <%= f.select :status, Comment::STATUS %><br>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_status.html.erb
<% i = 1 %>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Store</th>
                <th scope="col">Case Number</th>
                <th scope="col">Date Received</th>
                <th scope="col">Name</th>
                <th scope="col">Phone</th>
                <th scope="col">Issue</th>
                <th scope="col">Source</th>
                <th scope="col">Type</th>
                <th scope="col">Status</th>
                <th scope="col">Updates</th>
                <th scope="col">Days Open</th>
            </tr>
        </thead>
        <tbody>
            <% @comments.each do |c| %>
                <tr>
                    <th scope="row"><%= i %></th>
                    <td><%= c.store.store_number %></td>
                    <td><%=link_to c.case_number, comment_path(c) %></td>
                    <td><%= c.visit_date.strftime("%m/%d/%Y") %></td>
                    <td><%= c.guest.first_name + " " + c.guest.last_name %></td>
                    <td><%= c.guest.phone %></td>
                    <td><%= c.first_issue %></td>
                    <td><%= c.source %></td>
                    <td><%= c.comment_type %></td>
                    <td><%= c.status %></td>
                    <td><%= c.comment_updates.count %></td>
                    <td><%= Integer((Time.now - c.created_at)/86400) %></td>
                </tr>
                <% i = i + 1 %>
            <% end %>
        </tbody>
    </table>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/guest_comments.html.erb
<h1>Guest's Comments</h1>
<%= render 'status'%>

app/views/comments/index.html.erb
<h1>All Comments</h1>
<%= render 'status'%>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/open.html.erb
<h1>Open Comments</h1>
<%= render 'status'%>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Case Number : <%= @comment.case_number %></h1>
<p><%= @comment.store.store_number %> Incident Date: <%= @comment.visit_date.strftime("%m/%d/%Y") %> Time: <%= @comment.visit_time.strftime("%I:%M %p") %> Status: <%= @comment.status %> <br>
    Guest: <%= @comment.guest.first_name + " " + @comment.guest.last_name %> Phone: <%= @comment.guest.phone %> Email: <%= @comment.guest.email %><br>
     Main Issue: <%= @comment.first_issue %>  Updates <%= @comment.comment_updates.count %> <br>
    Issue Details: <%= @comment.first_issue_comment %> </p>
<% if !@comment.comment_updates.empty? %>
    <h3>Updates</h3>
    <% @comment.comment_updates.each do |u| %>
        <p>Date: <%= u.update_date.strftime("%m/%d/%Y") %> Contacted By: <%= u.employee_name %><br>
        Details: <%= u.current_update %></p>
    <% end %>
<% end %>
<% if session[:position] == "Office" %>
    <% if @comment.status == "Open" %>
        <button class="button button-light"><%= link_to 'Edit Comment', edit_comment_path(@comment) %></button>
        <button class="button button-light"><%= link_to 'Update Comment', new_comment_comment_update_path(@comment) %></button>
    <% end %>
    <button class="button button-light"><%= link_to 'Remove Comment', comment_path(@comment), method: :delete, data: {confirm: 'Are you sure?' } %></button>
<% end %>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>