config/routes.rb
Rails.application.routes.draw do
  resources :comment_updates
  resources :guests
  resources :comments do
    resources :comment_updates, only: [:new, :create, :index]
  end
  resources :stores
  root 'sessions#index'
  resources :users
  get '/open' => 'comments#open'
  get '/guest_comments' => 'comments#guest_comments'
  get '/find_comment' => 'comments#find'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/store_type' => 'stores#store_type'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :comments
    has_many :guests, through: :comments
    has_many :shops

    STORE_TYPE = ["Traditional", "WM"]
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :require_log_in
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
  end

  # GET /stores/1/edit
  def edit
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
  end

  # POST /stores
  # POST /stores.json
  def create
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    else
      @store = Store.new(store_params)
      respond_to do |format|
        if @store.save
          format.html { redirect_to @store, notice: 'Store was successfully created.' }
          format.json { render :show, status: :created, location: @store }
        else
          format.html { render :new }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    else
      respond_to do |format|
        if @store.update(store_params)
          format.html { redirect_to @store, notice: 'Store was successfully updated.' }
          format.json { render :show, status: :ok, location: @store }
        else
          format.html { render :edit }
          format.json { render json: @store.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    else
      @store.destroy
      respond_to do |format|
        format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def store_type
    @stores = Store.all
    render json: @stores
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :store_number, :store_email, :street_address, :city, :state, :zip_code,
        :phone, :owner_id, :director_id, :om_id, :supervisor_id, :gm_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |f| %>
    <div class="form-group">
        <%= f.label :name, "Restaurant Name" %>
            <%= f.text_field :name, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :name, "Restaurant Number" %>
            <%= f.text_field :store_number, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :store_type, "Restaurant Type" %>
            <%= f.select :store_type, Store::STORE_TYPE, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :gm_id, "Restaurant GM" %>
            <%= f.collection_select(:gm_id, User.all, :id, :full_name ) %>
    </div>
    <div class="form-group">
        <%= f.label :name, "Restaurant Email" %>
            <%= f.text_field :store_email, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :name, "Street Address" %>
            <%= f.text_field :street_address, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :name, "City" %>
            <%= f.text_field :city, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :name, "state" %>
            <%= f.text_field :state, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :name, "Zip Code" %>
            <%= f.text_field :zip_code, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :name, "Phone Number" %>
            <%= f.text_field :phone, class: "form-control", required: "true" %>
    </div>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurant List</h1>
    <div class="row">
        <% @stores.each do |s| %>
                <div class="col-sm-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><%= link_to s.store_number, store_path(s) %> <%= s.name %></h5>
                            <p class="card-text">Comments - <%= s.comments.where("status"=>"Open").count  %> Open <%= s.comments.where("status"=>"Closed").count %> Closed<br>
                                Work Orders - <%=  %> Open <%=  %> Closed<br>
                                Shop Score - XX% MTD  XX% QTD XX% YTD</p>
                        </div>
                    </div>
                </div>
        <% end %>
    </div>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @store.store_number + " " + @store.name %></h1>
<p>GM: <%= User.find(@store.gm_id).full_name + " Phone: " +  + " Email: " + @store.store_email %><br>
    Address:  </p>


<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>