config/routes.rb
Rails.application.routes.draw do
  resources :comment_updates
  resources :guests
  resources :comments do
    resources :comment_updates, only: [:new, :create, :index]
  end
  resources :stores
  root 'sessions#index'
  resources :users
  get '/open' => 'comments#open'
  get '/guest_comments' => 'comments#guest_comments'
  get '/find_comment' => 'comments#find'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/store_type' => 'stores#store_type'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, :position, :username, :password, presence: true
    validates :username, :email, uniqueness: true
    has_secure_password
    has_many :comments
    has_many :comment_updates
    has_many :shops


    POSITIONS = ["Owner", "Director", "Operations Manager", "Maint Department Head", "Supervisor", "General Manager", "Manager", "Field Tech", "Office"]

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_log_in
  # GET /users
  # GET /users.json
  def index
    if is_admin && session[:authority] != 6
      @users = User.all
    else
      redirect_to user_path(session[:user_id]) and return
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if @user.id != session[:user_id]
      redirect_to user_path(session[:user_id])
    end
  end

  # GET /users/new
  def new
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if !is_admin
      if @user.id != session[:user_id]
        redirect_to user_path(session[:user_id]) and return
      else
        render :edit
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    else
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if !is_admin
      if @user.id != session[:user_id]
        redirect_to user_path(session[:user_id]) and return
      end
    end

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if !is_admin
      redirect_to user_path(session[:user_id]) and return
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:first_name, :last_name, :email, :position, :username, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
    <div class="form-group">
        <%= f.label :first_name, "First Name" %>
            <%= f.text_field :first_name, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :last_name, "Last Name" %>
            <%= f.text_field :last_name, class: "form-control", required: "true" %><br>
    </div>
    <% if session[:authority] === 1 %>
      <div class="form-group">
          <%= f.label :position, "Position" %>
              <%= f.select :position, User::POSITIONS, class: "form-control", required: "true" %>
      </div>
    <% end %>
    <div class="form-group">
        <%= f.label :email, "Email Address" %>
            <%= f.text_field :email, class: "form-control", required: "true" %><br>
    </div>
    <div class="form-group">
        <%= f.label :username, "Create a Username" %>
            <%= f.text_field :username, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :password, "Create a password" %>
            <%= f.password_field :password, class: "form-control", required: "true" %><br>
    </div>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User List</h1>
    <div class="row">

<% @users.each do |s| %>
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><%= s.first_name + "   " + s.last_name %></h5>
                    <p class="card-text"><%= s.position %> </p>
                    <a href="users\<%= s.id %>\edit" class="btn btn-light">Edit User</a>
                     <%= link_to 'Delete User', user_path(s), method: :delete, class: "btn btn-danger" %>
                </div>
            </div>
        </div>
<% end %>
    </div>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row" >
    <div class="col" style="margin-bottom: 10px;">
        <div class="card text-dark" style="height: 100%;background-color: #EEECE0;">
            <div class="card-body" style="box-shadow: 6px 8px 6px black;">
                <h5 class="card-title text-center">Users</h5>
                <div class="row justify-content-md-center">
                    <% if session[:authority] === 1 %>
                        <%= link_to 'All Users', users_path, :class => "btn btn-light" %> |
                        <%= link_to 'Add User', new_user_path, :class => "btn btn-light" %> |
                    <% end %>
                    <%= link_to 'Edit My Info', edit_user_path(@user), :class => "btn btn-light" %>
                </div>
            </div>
        </div>
    </div>
    <div class="col" style="margin-bottom: 10px;">
        <div class="card text-dark" style="height: 100%;background-color: #EEECE0;"  >
            <div class="card-body" style="box-shadow: 6px 8px 6px black;">
                <h5 class="card-title text-center">Comments</h5>
                <div class="row justify-content-md-center" >
                    <% if session[:authority] === 1 || session[:authority] === 6 %>
                        <%= link_to 'Open Comments', open_path, :class => "btn btn-light" %> |
                        <%= link_to 'Add Comment', new_comment_path, :class => "btn btn-light" %>
                    <% end %>
                </div>
                <div class="row justify-content-md-center" style="margin-top:10px;" >
                    <%= form_tag("/find_comment", method: "get") do %>
                        <%= label_tag(:case_number, "Case Number:") %>
                        <%= text_field_tag(:case_number) %>
                        <%= submit_tag("Search", class:"btn btn-light")%>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col" style="margin-bottom: 10px;">
        <div class="card text-dark" style="height: 100%;background-color: #EEECE0;" >
            <div class="card-body" style="box-shadow: 6px 8px 6px black;">
                <h5 class="card-title text-center">Restaurants</h5>
                <div class="row justify-content-md-center">
                    <%= link_to 'All Restaurants', stores_path, :class => "btn btn-light" %>
                    <% if session[:authority] === 1 || session[:authority] === 6 %> |
                        <%= link_to 'Add Restaurant', new_store_path, :class => "btn btn-light" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <% if session[:authority] === 1 || session[:authority] === 2 || session[:authority] === 3 || session[:authority] === 6 %>
        <div class="col" style="margin-bottom: 10px;">
            <div class="card text-dark" style="height: 100%;background-color: #EEECE0;"  >
                <div class="card-body" style="box-shadow: 6px 8px 6px black;">
                    <h5 class="card-title text-center">Guests</h5>
                    <div class="row justify-content-md-center">
                        <%= link_to 'All Guests', guests_path, :class => "btn btn-light" %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>
<%
=begin%>
 <div class="row">
    <div class="col">
        <div class="card text-dark" style="height: 100%;background-color: #EEECE0;" >
            <div class="card-body" style="box-shadow: 6px 8px 6px black;">
                <h5 class="card-title text-center">Shops</h5>
                <div class="row justify-content-md-center">
                    <%= link_to 'All Shops', shops_path, :class => "btn btn-light" %>
                    <%= link_to 'Add Shop', new_shop_path, :class => "btn btn-light" %>
                </div>
            </div>
        </div>
    </div>
</div> 
<%
=end%>